### ISSUE TITLE
Modifying loaded fixture data permanently modifies fixture data

### ISSUE THREAD

**Issue by jamesbrobb** [billtrik/karma-fixture#12]
I have a `beforeEach` that loads a fixture and then several `it` statements that use that data to create a model.

The logic i'm testing modifies the mock data object that's created by the fixture load and i've noticed that this modification persists from one `it` to the next. I've tried using `cleanup()` in an `afterEach` but it makes no difference.

I'm presuming that once the json fixture is loaded it's cached as an object and that same objects is returned. So any modification to that object then persists. Unless i'm doing something wrong?

```
describe('my test', function() {

    var mockData;

    function changeSomeValueToB(data) {
        data.someValue = 'B';
    }

    beforeEach(function() {
        mockData = fixture.load('my/mock/data.fixture.json');
    });

    afterEach(function() {
        fixture.cleanUp();
    });

    it('should do something', function() {
        expect(mockData.someValue).toBe('A'); // passes
        changeSomeValueToB(mockData);
    });

    it('should do something else', function() {
        expect(mockData.someValue).toBe('A'); // fails
        expect(mockData.someValue).toBe('B'); // passes
    });
});
```

**Comment by nzakas** [comment]
It looks like the code is relying on `json-fixtures` for the JSON loading functionality, and it appears that `json-fixtures` caches data each time.

**Comment by billtrik** [comment]
Hello @jamesbrobb 
You can find the fix in the latest version of the plugin. (0.2.6)

Good catch by the way.
