### ISSUE TITLE
Same fixture object returned on multiple loads

### ISSUE THREAD

**Issue by epb-644** [billtrik/karma-fixture#14]
I just found a bug in my code caused by this unexpected behavior of `fixture.load`:

```
let fixtureObj = fixture.load('myfixture.json')
console.log(fixtureObj.testVal) // -> prints "undefined" (which is expected)
fixtureObj.testVal = 'foo'
fixtureObj = fixture.load('myfixture.json')
console.log(fixtureObj.testVal) // -> prints "foo" (which is not expected)
```

It seems that `fixture.load` returns the same instance of the object on each call, and thus subsequent calls will see any mutations on the object.

Would it be possible to deep clone the object before returning it via `fixture.load`? This would eliminate the issues I've seen.

**Comment by billtrik** [comment]
Hey @eddieburns55,

This was fixed in 0.2.6

please check https://github.com/billtrik/karma-fixture/issues/12#issuecomment-183728932
