### ISSUE TITLE
Warning: No provider for "framework:fixture"!

### ISSUE THREAD

**Issue by rockyromano** [billtrik/karma-fixture#16]
Unable to build as I receive this warning. One note, which I assume is unrelated, is that I only deviate from the docs in that I'm using "karma-ng-html2js-preprocessor" instead of "karma-html2js-preprocessor". But again, based on the error I don't see how this relates.

**Comment by kiran3807** [comment]
Hey, I had the same error too, putting 'karma-fixture' in the plugins array of karma config file solved the problem for me

**Comment by billtrik** [comment]
Reproduced from my side as well and fixed as proposed by @kiran3807. 

From my experience, if you define the plugins key in your conf for some plugin, 
you should manually include every other plugin you use.

I had already included the solution in the README but not with this exact error message. 
Will update
