### ISSUE TITLE
Evaluate JS specified through 'src' attribute for <script> tag

### ISSUE THREAD

**Issue by dinvlad** [billtrik/karma-fixture#19]
Hi all,

Is it possible to evaluate JavaScript when I specify it via the 'src' attribute instead of directly inside `<script>...</script>`? E.g. I'd like to execute

```
<!DOCTYPE html>
<script src="tested_code.js"></script>
```

and access the DOM elements created in the above script in a later test.

Thanks

**Comment by billtrik** [comment]
Hey @dinvlad.

Currently the implementation does not support that. I could do it, but i think this plugin should not handle that. If you want to load other dependencies on your test file, you should use other ways of loading them.

**Comment by dinvlad** [comment]
Thanks. In the end I've decided to automatically append the `<script>` tag after `<!DOCTYPE html>` to enable BrowserSync to be loaded when pages change (that was my main use case).
