### ISSUE TITLE
fixture.setBase() on global karma-shim.js

### ISSUE THREAD

**Issue by meriturva** [billtrik/karma-fixture#21]
I found your cool plugin for karma and it works! so thanks ...really.

Now i just would like to use `fixture.setBase()` on main global karma script....not in every spec files.
I have tried but without any success.
any advise?

**Comment by basiloungas** [comment]
Hey @meriturva,

I am really glad you find it helpful.

You could try to load before all your testing scripts,
some file which sets up the environment where you could put the above command.

For example you could try inside "karma.conf.js:":
```
...
   files: [
      ...
      'some_file_to_setup_test_env_to_be_loaded_before_your_specs.js',
      {pattern: 'spec/fixtures/**/*'},
      ...
    ],
...
```

**Comment by meriturva** [comment]
Great! it works!
i have created a file `karma-fixture.conf.js` with just 

`fixture.setBase("myFolder/mock");`

and loaded as you wrote!

So thanks!

**Comment by MagicDoctor365** [comment]
@meriturva @basiloungas  I'm quite confused the parameter of function setBase, is it a relative path ? if it's relative path, so which path is it relative to, the file I write the setBase, or set configuration in karma.config, could you make  it clear?

**Comment by meriturva** [comment]
@MagicDoctor365 
Here our solution:

1. create a file on root project: `karma-fixture.conf.src.js` with content: `fixture.setBase("relativeToRoot/mock");`
2. on `karma.conf.src.js`

```
frameworks: ['jasmine', 'fixture'],
        preprocessors: {
            "relativeToRoot/mock/**/*.json": ["json_fixtures"],
        },
       jsonFixturesPreprocessor: {
            variableName: '__json__'
        },
        files[
            "karma-fixture.conf.src.js",
              .......
       ]
```
3. on your unit test just call: `fixture.load("relativeToMockFolder/file.json");` (no setBase required anymore on spec files)
