### ISSUE TITLE
Throw error when fixture not found?

### ISSUE THREAD

**Issue by nzakas** [billtrik/karma-fixture#5]
I'm currently being bitten by an error that I've tracked down to `fixture.load()` not finding the file I requested. It looks like missing files are simply ignore and replace as an empty string (https://github.com/billtrik/karma-fixture/blob/master/src/fixture.coffee#L22), which makes it very hard to figure out what's going on.

Would you be open to throwing an error in that case?

**Comment by billtrik** [comment]
That makes sense. Will do

**Comment by billtrik** [comment]
@nzakas You can now update to 0.2.2 to get the update.

**Comment by nzakas** [comment]
Thanks!
